//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATNB_2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Product_MetaData))]
    public partial class Product
    {
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BidsOnProducts = new HashSet<BidsOnProduct>();
        }
    
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> OfferPrice { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public int productId { get; set; }
        public string image { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidsOnProduct> BidsOnProducts { get; set; }
    }
}
